# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'backupTool.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(561, 333)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 541, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit.setTabChangesFocus(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 2, 2, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.toolButton = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.toolButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushStart = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushStart.setObjectName("pushStart")
        self.verticalLayout.addWidget(self.pushStart)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 561, 21))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtWidgets.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        self.menuBackup_Quelle = QtWidgets.QMenu(self.menubar)
        self.menuBackup_Quelle.setObjectName("menuBackup_Quelle")
        self.menuHilfe = QtWidgets.QMenu(self.menubar)
        self.menuHilfe.setObjectName("menuHilfe")
        self.menuBauckasten = QtWidgets.QMenu(self.menubar)
        self.menuBauckasten.setObjectName("menuBauckasten")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionBeenden = QtWidgets.QAction(MainWindow)
        self.actionBeenden.setObjectName("actionBeenden")
        self.actionInternet = QtWidgets.QAction(MainWindow)
        self.actionInternet.setCheckable(True)
        self.actionInternet.setChecked(True)
        self.actionInternet.setEnabled(False)
        self.actionInternet.setObjectName("actionInternet")
        self.actionLokal = QtWidgets.QAction(MainWindow)
        self.actionLokal.setCheckable(True)
        self.actionLokal.setObjectName("actionLokal")
        self.actionAnleitung = QtWidgets.QAction(MainWindow)
        self.actionAnleitung.setObjectName("actionAnleitung")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNPage = QtWidgets.QAction(MainWindow)
        self.actionNPage.setCheckable(True)
        self.actionNPage.setChecked(True)
        self.actionNPage.setEnabled(False)
        self.actionNPage.setObjectName("actionNPage")
        self.actionWebHostel = QtWidgets.QAction(MainWindow)
        self.actionWebHostel.setCheckable(True)
        self.actionWebHostel.setObjectName("actionWebHostel")
        self.menuDatei.addAction(self.actionStart)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionBeenden)
        self.menuBackup_Quelle.addAction(self.actionInternet)
        self.menuBackup_Quelle.addAction(self.actionLokal)
        self.menuHilfe.addAction(self.actionAnleitung)
        self.menuHilfe.addAction(self.actionAbout)
        self.menuBauckasten.addAction(self.actionNPage)
        self.menuBauckasten.addAction(self.actionWebHostel)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuBackup_Quelle.menuAction())
        self.menubar.addAction(self.menuBauckasten.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JaskoScript.net: GB backup Tool"))
        self.label.setText(_translate("MainWindow", "Backup Quellen:"))
        self.plainTextEdit.setPlaceholderText(_translate("MainWindow", "http://meine_seite.npage.de/guestbook.html;"))
        self.label_2.setText(_translate("MainWindow", "Back-up-Datei: "))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "gb_backup.db"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.pushStart.setText(_translate("MainWindow", "Backup starten"))
        self.menuDatei.setTitle(_translate("MainWindow", "Datei"))
        self.menuBackup_Quelle.setTitle(_translate("MainWindow", "Backup Quelle"))
        self.menuHilfe.setTitle(_translate("MainWindow", "Hilfe"))
        self.menuBauckasten.setTitle(_translate("MainWindow", "Bauckasten"))
        self.actionStart.setText(_translate("MainWindow", "Backup Starten"))
        self.actionStart.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionBeenden.setText(_translate("MainWindow", "Beenden"))
        self.actionBeenden.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionInternet.setText(_translate("MainWindow", "Internet"))
        self.actionLokal.setText(_translate("MainWindow", "Lokal"))
        self.actionAnleitung.setText(_translate("MainWindow", "Anleitung"))
        self.actionAbout.setText(_translate("MainWindow", "Über uns"))
        self.actionNPage.setText(_translate("MainWindow", "nPage"))
        self.actionWebHostel.setText(_translate("MainWindow", "Web-Hostel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

